In [ ]:
# Load the 'All' sheet to check its structure
import pandas as pd
all_sheet_data = pd.read_excel("DATA BASE 2020 BATCH.xlsx", sheet_name='All')

# Display the first few rows and columns
all_sheet_data.head(), all_sheet_data.columns

FileNotFoundError: [Errno 2] No such file or directory: 'DATA BASE 2020 BATCH.xlsx'

In [ ]:
# Load the 'All' sheet to check its structure
import pandas as pd
all_sheet_data = pd.read_excel("/content/Book1.xlsx")

# Display the first few rows and columns
all_sheet_data.head(), all_sheet_data.columns

(   Unnamed: 0  Unnamed: 1                              Unnamed: 2  \
 0         NaN         NaN                                    NAME
 1         NaN         NaN                                     NaN
 2         NaN         NaN            AGARWAL RAHUL NARENDRA RAJNI
 3         NaN         NaN  AGRAHARI SHUBHAM RAMNARAYAN SHOBHADEVI
 4         NaN         NaN  BHANDARI HARSHAL RAJENDRAKUMAR SANGITA

        Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6          Unnamed: 7
 0         CONSENT       CGPA         AY         TY  Test Score average
 1             NaN        NaN        NaN        NaN                 NaN
 2  Higher Studies   7.304106  79.654865        NaN                   0
 3       Placement   7.670918  88.235164  67.073171           85.096984
 4  Higher Studies   8.231932  83.051576        NaN                   0  ,
 Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
        'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7'],
       dtype='object'))

In [ ]:

import pandas as pd
all_sheet_data = pd.read_excel("/content/Book1.xlsx")

# Display the first few rows and columns
all_sheet_data.head(), all_sheet_data.columns

(                      NAME OF THE STUDENT         CONSENT      CGPA  \
 0                                     NaN             NaN       NaN
 1            AGARWAL RAHUL NARENDRA RAJNI  Higher Studies  7.304106
 2  AGRAHARI SHUBHAM RAMNARAYAN SHOBHADEVI       Placement  7.670918
 3  BHANDARI HARSHAL RAJENDRAKUMAR SANGITA  Higher Studies  8.231932
 4    BHANUSHALI CHARMI BABULAL JAYSHRIBEN  Higher Studies  7.718889

           AY         TY  TEST SCORE
 0        NaN        NaN         NaN
 1  79.654865        NaN    0.000000
 2  88.235164  67.073171   85.096984
 3  83.051576        NaN    0.000000
 4  80.682912        NaN    0.000000  ,
 Index(['NAME OF THE STUDENT', 'CONSENT', 'CGPA', 'AY', 'TY', 'TEST SCORE'], dtype='object'))

In [ ]:
df = pd.read_excel('/content/Book1.xlsx')
placement_df = df[df['CONSENT'] == 'Placement']
print(placement_df)

                             NAME OF THE STUDENT    CONSENT      CGPA  \
2         AGRAHARI SHUBHAM RAMNARAYAN SHOBHADEVI  Placement  7.670918
6                    BHOIR LAVESH SURESH SANGITA  Placement  7.781643
7                GUPTA VICKY NUTANPRAKASH KRANTI  Placement  5.773961
11   CHAURASIA BRIJESH HARIHAR PRASAD URMILADEVI  Placement  7.744831
13                        DALVI ANKIT UDAY JYOTI  Placement  8.275604
..                                           ...        ...       ...
777                     PAL VIKRANT SUNDER SUMAN  Placement  7.782436
778                PAWAR KUNAL SHASHIKANT SNEHAL  Placement  7.712051
779             TRIPATHI ROHIT GANGASHARAN MEERA  Placement  7.743590
780        RAKHOLIYA URVASHI BHIKHUBHAI BHANUBEN  Placement  8.576667
781           VASOLIYA RINKAL VINODBHAI NEETABEN  Placement  7.769103

            AY         TY  TEST SCORE
2    88.235164  67.073171   85.096984
6    71.071052  14.285714    0.000000
7    75.000000        NaN    0.000000
11   87.705718  81.707317   72.459193
13   86.480031  75.609756   93.152174
..         ...        ...         ...
777  66.588050        NaN    0.000000
778  65.879874  23.880597    0.000000
779  57.712579  16.853933    0.000000
780  87.967296  71.276596   61.515152
781  87.550943  73.404255   46.734007

[471 rows x 6 columns]

In [ ]:
df = pd.read_excel('/content/Book1.xlsx')
placement_df = df[df['CONSENT'] == 'Placement']
df.to_excel('updated_file.xlsx', index=False)

In [ ]:
df=pd.read_excel('/content/updated_file.xlsx')
df.head()

,NAME OF THE STUDENT,CONSENT,CGPA,AY,TY,TEST SCORE
0,NaN,NaN,NaN,NaN,NaN,NaN
1,AGARWAL RAHUL NARENDRA RAJNI,Higher Studies,7.304106,79.654865,NaN,0.000000
2,AGRAHARI SHUBHAM RAMNARAYAN SHOBHADEVI,Placement,7.670918,88.235164,67.073171,85.096984
3,BHANDARI HARSHAL RAJENDRAKUMAR SANGITA,Higher Studies,8.231932,83.051576,NaN,0.000000
4,BHANUSHALI CHARMI BABULAL JAYSHRIBEN,Higher Studies,7.718889,80.682912,NaN,0.000000

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

MessageError: Error: credential propagation was unsuccessful

In [ ]:
placement_df = df[df['CONSENT'] == 'Placement']

placement_df.to_excel('placement_data.xlsx', index=False)

In [ ]:
# prompt: Top rows from placement_data.xlxs

import pandas as pd
placement_df = pd.read_excel('/content/placement_data.xlsx')
placement_df.head()

,NAME OF THE STUDENT,CONSENT,CGPA,AY,TY,TEST SCORE
0,AGRAHARI SHUBHAM RAMNARAYAN SHOBHADEVI,Placement,7.670918,88.235164,67.073171,85.096984
1,BHOIR LAVESH SURESH SANGITA,Placement,7.781643,71.071052,14.285714,0.000000
2,GUPTA VICKY NUTANPRAKASH KRANTI,Placement,5.773961,75.000000,NaN,0.000000
3,CHAURASIA BRIJESH HARIHAR PRASAD URMILADEVI,Placement,7.744831,87.705718,81.707317,72.459193
4,DALVI ANKIT UDAY JYOTI,Placement,8.275604,86.480031,75.609756,93.152174

In [ ]:
df = pd.read_excel('/content/placement_data.xlsx')
df['CATEGORY'] = df.apply(
              lambda row: Category_1 if row['CGPA'] >= 7.84 and row['AY'] >= 75 and row['TY'] >= 75 and row['TEST SCORE'] >= 75 else
                          Category_2 if row['CGPA'] >= 6.77 and row['AY'] >= 75 and row['TY'] >= 65 and row['TEST SCORE'] >= 65 else
                          Category_3 if row['CGPA'] < 6.77 and row['AY'] >= 75 and row['TY'] < 65 and row['TEST SCORE'] < 65 else
                          Category_4, axis=1)
print(df)
df.to_excel('updated_file.xlsx', index=False)

NameError: name 'Category_2' is not defined

In [ ]:
import pandas as pd

# Define category names or values
Category_1 = 'Category 1'
Category_2 = 'Category 2'
Category_3 = 'Category 3'
Category_4 = 'Category 4'

# Read the Excel file
df = pd.read_excel('/content/placement_data.xlsx')

# Apply the lambda function to categorize
df['CATEGORY'] = df.apply(
    lambda row: Category_1 if row['CGPA'] >= 7.84 and row['AY'] >= 75 and row['TY'] >= 75 and row['TEST SCORE'] >= 75 else
                Category_2 if row['CGPA'] >= 6.77 and row['AY'] >= 75 and row['TY'] >= 65 and row['TEST SCORE'] >= 65 else
                Category_3 if row['CGPA'] < 6.77 and row['AY'] >= 75 and row['TY'] < 65 and row['TEST SCORE'] < 65 else
                Category_4, axis=1)

# Print the DataFrame to verify
print(df)

# Save the updated DataFrame to a new Excel file
df.to_excel('updated_file.xlsx', index=False)

                             NAME OF THE STUDENT    CONSENT      CGPA  \
0         AGRAHARI SHUBHAM RAMNARAYAN SHOBHADEVI  Placement  7.670918
1                    BHOIR LAVESH SURESH SANGITA  Placement  7.781643
2                GUPTA VICKY NUTANPRAKASH KRANTI  Placement  5.773961
3    CHAURASIA BRIJESH HARIHAR PRASAD URMILADEVI  Placement  7.744831
4                         DALVI ANKIT UDAY JYOTI  Placement  8.275604
..                                           ...        ...       ...
466                     PAL VIKRANT SUNDER SUMAN  Placement  7.782436
467                PAWAR KUNAL SHASHIKANT SNEHAL  Placement  7.712051
468             TRIPATHI ROHIT GANGASHARAN MEERA  Placement  7.743590
469        RAKHOLIYA URVASHI BHIKHUBHAI BHANUBEN  Placement  8.576667
470           VASOLIYA RINKAL VINODBHAI NEETABEN  Placement  7.769103

            AY         TY  TEST SCORE    CATEGORY
0    88.235164  67.073171   85.096984  Category 2
1    71.071052  14.285714    0.000000  Category 4
2    75.000000        NaN    0.000000  Category 4
3    87.705718  81.707317   72.459193  Category 2
4    86.480031  75.609756   93.152174  Category 1
..         ...        ...         ...         ...
466  66.588050        NaN    0.000000  Category 4
467  65.879874  23.880597    0.000000  Category 4
468  57.712579  16.853933    0.000000  Category 4
469  87.967296  71.276596   61.515152  Category 4
470  87.550943  73.404255   46.734007  Category 4

[471 rows x 7 columns]